### ISSUE TITLE
validation bug !

### ISSUE THREAD

**Issue by heyadityak** [dhruvp-8/User-Management-System#1]
There's a minor validation bug in your system.(Don't know if it's a bug or a feature)

The registrations are not accepted when the email ID is having periods (e.g. `aditya.kkumar97@gmail.com` )

I have attached the screenshot as follows:

![bugreport](https://cloud.githubusercontent.com/assets/15857647/24300438/76a1f418-10d2-11e7-8af8-511e988ac268.PNG)

By the way, the project's good. I particularly liked the email authentication part (_I guess you have used SendGrid for mass-mail handling_)

- @beingadityak

**Comment by dhruvp-8** [comment]
Thanks for reporting the bug!
I think there is a problem with regex, will fix it soon.
